language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - composer install --no-interaction --prefer-source

script:
  - phpunit --coverage-text

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml

git:
  depth: 5
